
spring:
  application:
    name: ms-partner
  datasource:
    url: jdbc:postgresql://localhost:5432/db_socios
    username: userSociosSigap
    password: systemSociosSigap2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Crea/Actualiza las tablas automaticamente a partir de las entidades
    show-sql: true      # Permite mostrar las consultas en la consola
server:
  port: 4041
