spring:
  profiles:
    default: default
  application:
    name: ms-auth-server
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5435/db-users
    username: userAdminSigap
    password: user_admin_sigap2026
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 3000
  servlet:
    context-path: /ms-auth-server
